spring:
  application:
    name: eureka-server
  profiles:
    active: local

server:
  port: 3000

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:3000/eureka


