spring:
  application:
    name: spring-boot-demo-server
  profiles:
    active: local

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:3000/eureka

server:
  port: 3000


